name: Run Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter_test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          cache: true

      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --test-randomize-ordering-seed random

      - name: Update coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "========== Flutter Test Summary =========="
          sudo apt-get update && sudo apt-get install -y lcov
          genhtml coverage/lcov.info --output-directory coverage/html
          lcov --summary coverage/lcov.info
          echo "=========================================="
      
      - name: Upload Coverage HTML Report
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
